### ISSUE TITLE
Change client logging so we can get L1 IP address even when there's a network error

### ISSUE THREAD

**Issue by reidlw** [filecoin-saturn/js-client#33]
Also send node ID :)

High priority because of this: https://github.com/orgs/filecoin-saturn/projects/1/views/1?pane=issue&itemId=42979557

**Comment by AmeanAsad** [comment]
## Update:
- PR merged: https://github.com/filecoin-saturn/js-client/pull/35. New js-client release created.
- ready for arc deploy: https://github.com/Arc-io/core/pull/402
