### ISSUE TITLE
Add unixfs exporter range request test on multi-block file

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-saturn/js-client#49]
# What

See #48

Unit tests for extractVerifiedContent show it works with the range, but all tests are currently of a single block file.

Need to assemble a multi-block range response (probably best way is just to hit saturn with a manual `entity-bytes` param for a sizable file maybe on Web3 storage) and record to file

**Comment by wilkyr31d** [comment]
Hannah has reviewed @guanzo has some changes to make now

**Comment by wilkyr31d** [comment]
@guanzo reviewing feedback and making changes today

**Comment by guanzo** [comment]
addressed feedback, re-requested review from hannah

**Comment by guanzo** [comment]
merged
