### ISSUE TITLE
Integration test of range option

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-saturn/js-client#50]
# What

Requires #48 & #49

We need to be able to send a mock request to a saturn node, and send back a ranged file based on the entity bytes parameter. Probably we can just do this with hello.car

**Comment by guanzo** [comment]
PR: https://github.com/filecoin-saturn/js-client/pull/55

**Comment by guanzo** [comment]
in progress, will file PR on 1/24

**Comment by guanzo** [comment]
ETA today

**Comment by guanzo** [comment]
PR: https://github.com/filecoin-saturn/js-client/pull/58

**Comment by wilkyr31d** [comment]
@hannahhoward or @AmeanAsad to review PR
